---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/template.tex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# Reflective Based on In-Situ Observations within an Intensive Care Unit and Emergency Department {.unnumbered}

```{=tex}
\adjustmtc
\markboth{ICU}{}
```
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

In the preceding chapters, I have presented empirical results from experimental studies conducted during this DPhil that aimed to investigate confidence and information during medical diagnostic decisions. These studies have been designed to emulate certain aspects of the diagnostic process as it is carried out in real medical practice, such as investigating how the differentials being considered evolves over time with more information. I also aimed to use patient cases that were representative of the cases that clinicians encounter in real medical practice. In addition, I used a virtual reality methodology in Study 4 to simulate how patients can improve or deteriorate over time depending on the administration of treatment. Through this work, I believe that understanding the cognitive mechanisms of diagnoses has implications for real medical practice. I understand however that by using controlled experimental paradigms, I abstract away certain practicalities of real medical practice that can also impact diagnostic confidence and information seeking. 

\
In order to aid the judgement of this DPhil’s applicability and ecological validity as it pertains to medical practice, I conducted in-situ observations in two medical environments: Intensive Care (ICU) and Emergency Department (ED). I conducted observations during the morning handovers and ward rounds in ICU and during both day shifts and night shifts in ED. These observations took place between December 2023 and September 2024. In this chapter, I use these observations as a naturalistic grounding to discuss this DPhil’s strengths and limitations, as well as how the scenarios I emulated in this work do also come up in everyday medical practice. The points raised in this chapter are personal reflections from these in-situ observations, rather than rigorous qualitative findings. 

\
I start with a discussion of reflexivity from a personal and contextual standpoint to discuss the perspective from which the work stems from (using recommendations on discussing different types of reflexivity from Olmos-Vega et al., 2022). I then introduce the medical settings within which the observations were conducted, noting similarities and differences between them in terms of the work that clinicians do. Following this, I present instances of this DPhil’s key research interests on confidence, differential evaluation and information seeking as they arise in these medical environments. Finally, I evaluate the ecological validity of this DPhil in terms of the aspects of these medical environments that are captured or not by this DPhil and its empirical studies. This contributes to the Overall Discussion section by grounding the strengths and limitations of the work in observations of medical practice.

## Reflexivity {.unnumbered}

I personally started researching on medical decision making during my MSc degree in Human-Computer Interaction from University College London during a thesis project looking at perfusion data visualisation during paediatric cardiac surgery. As part of this project, I conducted in-situ observations and interviews within a children’s hospital. During the same degree, I also conducted interviews for a project to design a visualisation tool for monitoring the flow of patients in and out of ICU. Both of these projects positively contributed to my interest in studying medical decisions in more detail during my DPhil. My own perspective as a researcher stems from a desire to study situations that are based on real-world decisions with high impact and stakes, such that I hope for my own research to have an impact (however small). My experience conducting this research has reshaped my perspective on medical decisions and healthcare as a whole, via my collaboration with several clinical faculty/researchers and through the observations of clinicians at work (as discussed in the chapters). 

\
From a contextual perspective, this work (as well as the observations presented in this chapter) was conducted in the UK, with a particular focus on medical students and staff based in Oxford’s John Radcliffe Hospital. Public healthcare in the UK is conducted under the governance of the National Health Service (NHS). Over the course of the DPhil, the NHS was a constant topic for reporting by UK news outlets, given the consequences for healthcare in the wake of the global COVID-19 pandemic and national strikes by healthcare workers due to pay disputes and understaffing. As noted in the systematic scoping review, contextual factors have been shown to impact clinician confidence. The specific context of this work (and the observations presented in this chapter) should not be considered as representative of healthcare as a whole (either in other parts of the UK or in other countries). It is hoped however that the focus on the cognitive psychology of diagnoses allows for insights that have aspects of generalisability to other medical contexts. 

## ICU {.unnumbered}

ICU is primarily a support unit that is relatively agnostic with regards to medical subdisciplines. The primary aim of the unit is to provide ongoing care for acutely unwell patients in a supportive capacity rather than a remedial one. Hence, clinicians and nurses in ICU are limited in what they can do for patients in their care. ICU can be hugely beneficial for patients by providing urgent care for them in hopes of aiding their road to recovery. Patients then tend to move elsewhere in the hospital, such as the main ward or to the theatre for surgical intervention. As mentioned earlier, ICU sits outside of other medical subdisciplines. It is hence very frequent that individuals working in ICU are required to bring in external advice from other departments in the hospital, such as Rheumatology, Neurology, Surgery, Vascular or Trauma. ICU is then a department that involves many individuals, both from within and outside its remit. Quickly and temporarily formed teams then have to collaborate on a patient and align their mental models. It is very common for teams of individuals to work together despite having little to no prior experience with each other.

\
In brief, ICU is usually a point of transition for patients within their medical pathway through the hospital, with other departments feeding into and being fed from ICU. But ICU can also be the last point in their patient journey (either positively or negatively).

\
Perhaps the most focal decisions that consultants within ICU have to make involves monitoring ICU capacity in the present and in the future. Every ICU unit has a limited capacity in terms of the number of beds available and hence the number of patients who can be cared for at any given time (this was 22 beds for the unit observed). These issues to do with capacity are of course related to actions of those in ICU but are also inexorably linked to wider environmental factors. This includes funding for increased ICU capacity and staffing as well as structural or technological issues within the hospital and region/NHS trust as a whole. During one of our observation sessions, the unit was understaffed relative to the required number of staff needed to manage the unit. A patient is able to leave ICU and hence free up a bed if they either improve enough to transition to another unit in the hospital or if they unfortunately die in ICU. However, because ICU is merely a support unit, patients can also find themselves in the unit for a longer period with very slow improvement or deterioration. As a result, patients can sometimes stay in ICU for weeks or even months on end. Clinicians and nurses in ICU have to balance what they can realistically do for a patient within their remit whilst being cognizant of the longer-term outcome of the patient. This is best summed up by one clinician who said during observations: “there is balance of what we can do and what is kind (to the patient).”

## Emergency Department {.unnumbered}

The Emergency Department (ED, sometimes referred to as Accident & Emergency or A&E) is part of the hospital that is designed to deal with urgent or life-threatening patients. Whilst some patients may be admitted from other hospitals (if they are especially serious), most patients are individuals who have walked in to report their case and symptoms. An issue that this presents is that a lot of patients may report to ED with non-serious conditions (e.g. a migraine). This demands time from clinicians that could otherwise be allocated to more serious patients. Whilst observing a registrar in ED, they remarked that they tend to see patients quickly and use pattern recognition so that they can quickly identify patients who require more urgent care. The ED observed was spread out over multiple sections, broadly separating patients into minor and major cases. Patients report to a reception area, where their details are recorded, and then stay in a waiting area until they are called to be seen by a clinician. Due to the number of patients who attend and the time it can take for certain tasks to be completed (e.g. getting test results, completing a patient’s discharge documentation), patients may have to wait for extended periods of time between instances of being seen by a clinician. After seeing the patient, clinicians in ED have a few possible options of how to proceed. If the case is not overly serious, patients could be sent home with some medical advice, a prescription for medication and/or safety netting (i.e. advice to return if the symptoms persist or worsen). If the case is more serious, patients may be admitted into the ED and given a bed for further treatment. Patients could also be transferred to other departments or hospitals for further observations or treatment. 

## Decision Making in Both Settings {.unnumbered}

I now note the observed commonalities between ICU and ED, firstly detailing aspects to do with the overall function of these departments and then focusing on aspects related to this thesis’s main research areas on confidence, information seeking and differential evaluation.

\
Firstly, both departments are involved in a large degree of coordination with other departments and other hospitals. Part of ICU’s coordination with other departments/hospitals are incoming requests for the admitting of new patients. This could include a patient who has experienced a complication during surgery or a patient who has been admitted from an outside hospital in need of urgent care. Capacity is constantly at a premium and it is at the forefront of an ICU consultant’s thinking. Ideally, the unit should be able to operate with a spare buffer capacity of one or two beds in case of an emergency. This spare capacity can be fairly rare to obtain however, as it can be due to factors outside of the control of ICU clinicians. ICU can hence act as a central coordinator of several decision makers who are involved with a particular patient’s care whilst clinicians within ICU itself will not be able to do too much without the involvement of these other departments. ICU clinicians still have primary responsibility for patients whilst they are in the unit. As one clinician put it, “someone who has trauma is no longer Trauma’s responsibility.” For ED, there is a similar coordination with other departments in terms of seeking advice from other subdisciplines and with other hospitals to transfer patients. 

\
As an example, one observed patient had chemical burns all over their arms. After receiving treatment and cleaning of the wounds, the patient reported pain and tingling in the arms. This suggested a possibility of compartment syndrome, where the pressure around the muscles can cause restricted blood flow. If left untreated, the patient may require surgery (known as fasciotomy) to relieve the pressure. In order to query this diagnosis, the ED registrar sought the opinion of a consultant in the Plastic Surgery department. This was important, because the patient was to be transferred to a different hospital, which did not have capacity for the patient until the next day. If however the patient did have compartment syndrome, the other hospital would urgent free up capacity to admit the patient as soon as possible. Here in this example, it can be seen how ED involves both an external department and another hospital in the decision-making process, similar to ICU.

\
Another similarity between the two settings is in terms of documentation. A key activity observed during shifts in both ED and ICU was documenting the latest developments with the patient. The ‘record keeping’ for patients took up a significant portion of the clinicians’ time during the observed shifts. This took the form of a digital, centralised platform where clinicians recorded the latest observations of the patient and the current set of actions to be taken. Other information is also recorded here, such as test results and scans. Such a centralised documentation platform is useful for a setting with rotating on and off shifts, such that a clinician can view what another clinician documented previously for a patient, easing the transition of care between medical staff. If such documentation is not done thoroughly and clearly, this can create a source of confusion and uncertainty for staff currently caring for a patient, as they may be unsure about what care/tests were previously carried out. This should be noted as a specific facet of this hospital, as other hospitals in the UK (let alone in other countries) do not have computerised platforms to record all information pertaining to each patient. Many hospitals make use of simple paper documentation instead, which is more likely to lead to situations of past documentation for a patient not being available. When a clinician first sees a patient during their shift, the starting point they have in terms of a patient's medical history is dependent on the documentation available from those clinicians who had previously treated the patient. Some patients may also bring documentation they had received from other hospitals to aid the clinician in their initial understanding of the patient’s condition. Taken together, the act of recording the patient’s trajectory throughout their time in hospital is useful for ensuring a smooth transition of care to other staff, departments and hospitals.

## Uncertainty {.unnumbered}

I now discuss and compare how diagnostic uncertainty arises in both departments, as it can manifest differently within ICU and ED.  

\
In both departments, the state of a patient can change fairly quickly as a sudden development in their situation can occur over a single shift. This is why, at least in the departments I observed, there is a regular cadence of communication. This comprises a morning handover, where the consultant during the night shift hands over to the day shift consultant and reports patient developments that occurred during the night. In ICU, clinicians performed morning, afternoon and evening ward rounds, during which the consultant visits each patient bed to receive updates on the patient by the caring nurses and (when possible) talk to the patient. During these ward rounds, the consultant will collaborate with the registrar, nurses and any individuals from other relevant departments to formally record an assessment of the patient and recommend a short-term action plan to be taken for that patient and to be coordinated with the attending nurses. This includes a formal assessment of whether the patient was clinically fit enough to be discharged (or if the department is not able to do much more for the patient given their capabilities). In ED, it was common for staff to check their understanding and plan for the patient with the registrar for that shift. This meant that clinicians tended to avoid making decisions on their own. These discussions between the clinicians and the registrar happened fairly regularly, such as when there was an update with the patient or a new test result. 

\
In sum, because the nature of a patient’s condition can change quickly, clinicians have to be in constant communication in order to regularly keep updated on the patient’s development. This reflects that diagnosis is a constantly evolving process as the understanding of the patient changes with time (even without considering new information or tests being made available about the patient). 

\
Before discussing how diagnostic uncertainty varies between ICU and ED, it is important to explain how broad diagnosis is. As became clear through observations, diagnosis is multi-faceted and can take multiple forms. Diagnosis is often not simply about identifying the condition that the patient has. It also involves identifying how severe the condition is, which pathophysiological system(s) is/are driving the symptoms, and the likely development of the condition over time. In ICU, there is usually a lot of information already available on the patient as they have likely already been admitted elsewhere in the hospital (in another department) prior to arriving in ICU. Hence, there has already been a recording of medical history and recent test results, meaning that there is usually not a lot of uncertainty about what condition the patient has. Rather, the real uncertainty stems not from the patient’s condition now, but the patient’s condition in the future, such as in 24-48 hours’ time. An ICU consultant may consider the following questions:
\

*	How bad ‘could’ this patient’s condition be relative to how unwell the patient is now?
*	What realistic milestones/goals can we set for this patient’s recovery plan?
*	Is the patient ‘wardable’? (i.e. is the patient well enough to be discharged from ICU and sent to the main hospital ward for continued care that is not as acute)

\
Making decisions about the current and future capacity of ICU is hence extremely complex, as it involves an understanding of each patient’s condition not only in the current moment but in the future. Essentially, how likely is the patient to improve or deteriorate? There is a projection of future state that occurs (as per the parlance of research on Situational Awareness). This occurs at the individual patient level, where clinicians imagine how well/unwell a patient will be in the short- or long-term future. This involves looking at the trend of treatment and what the upcoming milestone/endpoint for that patient might be. This can include simply getting the patient to eat solid food again or get up from their bed, or it could be tied to specific patient parameters (e.g. raising oxygen levels). This projection also occurs at the unit level, as the combination of each patient’s situation produces an overall picture of the unit’s available capacity to admit new patients. Finally, the projection can also take place over the entire NHS trust/region. During observations, the start of a morning shift began with the announcement that there was ‘no capacity across the trust’, meaning any incoming requests from other departments to admit patients to ICU would have to be refused.  
\
In ED however, the situations that clinicians encounter are much more about formulating an initial working diagnosis to guide subsequent care. This is because patients are, for the most part, visiting the hospital for the first time for this particular condition. The patient’s visit may also be the first point of contact with the healthcare system for the current ‘episode’ of a chronic/recurring condition. As a result, there may not be the same recording of information available on the patient as there is in ICU. Hence, initial information seeking is important in ED to develop a working assessment of the patient’s condition. The aforementioned ‘projection of future state’ is also important in ED, as clinicians aim to see serious/urgent patients as soon as possible. Much like ICU, there is a capacity of patients, both in terms of available beds (if needed for the patient) and in terms of staffing. The observed ED aimed to see all patients within a few hours and if some patients require more attention, this affects the allocation of attention to other patients. This is why the registrar had mentioned seeing patients quite quickly, such that severe patients/cases could be identified sooner in order to be prioritised. 

\
In both settings, clinicians had to formulate a trajectory for where the patient would go when they leave the department and what care is provided afterwards. If patients are sent to a different part of the hospital, this could reflect either an increase (e.g. moving from ED to ICU) or decrease (e.g. being discharged so that the patient can go home) in the patient’s severity. Clinicians were required to document this discharge process, in terms of where the patient was to go next and why. Discharging a patient may also require ‘safety netting’ to be put in place, which is when a clinician discusses with the patient and/or their next of kin about what to do if the symptoms recur or worsen in the coming days or weeks. This could include getting over-the-counter medication, visiting their GP or coming back to the hospital again. This safety netting process also includes understanding social factors that may have contributed to the patient’s condition. In ED, there were a few examples of elderly patients who may require home care visits and one example of a patient who was at risk of self-harming (which had brought them into ED in the first place) again. 

\
This projection of the patient’s future trajectory is a complex task and is in line with Situational Awareness research on taking one’s current understanding of a situation to forecast future outcomes. As a result, there is a different type of uncertainty that can be seen here which has not been explored as much in this DPhil. This assessment of the patient's future state can be prone to biases, as Graz et al. (2005) found that surgeons overestimated the improvement in patients' quality of life and recovery after their operation. Not only do clinicians experience uncertainty over what condition a patient may have in the present moment but also what their condition may look like in future (particular for long-term/chronic conditions that extend well beyond the patient’s time in hospital). In the observed ED, if a patient revisited the hospital with the same symptoms within 24 hours of being discharged, this would be counted as a ‘failed discharge’ and would be recorded as a key metric for the hospital/NHS trust’s performance. Hence, the uncertainty about the patient’s trajectory is one with practical consequences. 

\
A final ancillary point on uncertainty is its effects on patients in addition to clinicians. Patients are sometimes at the hospital for an extended period of time without a clear diagnosis or understanding of why they are experiencing the symptoms they have. Experiencing long-term/chronic or recurring conditions is a source of major stress for patients (and their next of kin) without a clear path to recovery. This came across in observations: one patient, for example, had already been to the hospital twice during the same year with recurring episodes of extreme fatigue and losses of consciousness. They lamented the fact that on previous occasions, clinicians were not able to identify a diagnosis for their condition. This underscores another aspect of diagnostic uncertainty and why it is important for future study: the impact that it has on patients in terms of their mental (as well as physical) wellbeing. Future work can also look at how diagnostic uncertainty impacts patients and ways that clinicians can mitigate the stress that patients feel through communication frameworks.

## Information Seeking {.unnumbered}

With regards to information seeking, clinicians in both settings were reliant on the recording from other clinicians. In particular, given that consultants and staff rotate their shifts, several clinicians have a hand in the treatment and care for a single patient. For each shift, clinicians record information on the actions and development of that patient during the shift. This means that in order to ensure smoothness in transitioning between clinicians, a clinician has to record information clearly such that the clinician on a given shift understands what took place during the previous one. Not recording information clearly can result in uncertain and inefficient situations. For instance, if a clinician does not record that a CT scan has been requested for a patient, a future clinician may request a second redundant scan without realising. In addition, a future clinician should know if a patient has already been given fluids (and when they were last administered) such as to not overload the patient. Clinicians were observed to vary in how detailed their reports/documentation of patients were, with some taking more time to record patient developments in a lot of detail. Without appropriate detail, there were observed to be moments of confusion for a clinician attempting to understand the recent medical history of a patient. 

\
A key aspect of information seeking in medical environments is that information can vary in their availability and ‘time cost’. Colleagues of clinicians are important for sharing expertise. A colleague may have been previously treating a patient and can then shed light on their recent medical history. A colleague may also be, as previously discussed, from another department in order to provide an additional necessary perspective on a patient. However, a colleague may not be available to provide their opinion when needed, as they may be preoccupied with other patients. Departments may have specialists (e.g. an ENT specialist) who do rounds of the hospital, but are not always present to provide assistance. When coupled with the rotation of staff, with different levels of experience with certain types of patients or procedures, the nature of the department’s expertise can vary on a day-to-day basis. In addition to information from others, information from test results can also carry a cost. If an X-ray is required for a patient, the X-ray machine (and its radiologists) would have to be available at the time of request. The test may then take time to organise, on top of the time it takes for the results to be made available. When information has a certain cost associated with it, clinicians may be more likely to focus on the information that they already have available to them. This 'availability bias' was cited as a cause of cognitive bias in one case study of a patient with an acute myocardial infarction (Schlögl et al., 2018).

\
A final aspect of information seeking to note is the role of colleagues, senior staff and other specialists. Decision making in both of these settings, among other medical settings, involves consultation with several colleagues. A consultant make ask the nurse who was seeing the patient during the night for an update, or ask for advice from senior or specialist staff. In both ICU and ED, staff were consistently in contact with staff from other departments (e.g. neurology, surgery, psychiatry). This seemed to not only be for advice seeking, but also for coordination purposes. Put simply, if a patient is experiencing trauma, the Trauma team has to be consulted as the patient case falls within their expertise (though this could be have a specific facet of the workplace environment where the observations took place and may not be the case in other settings). However, there is important information that can be gleaned from colleagues through this communication process that can be just as valuable as a patient’s test results. 

## Evaluation of Ecological Validity  {.unnumbered}

At this point, I shall discuss the ways in which theoretical concepts and empirical work conducted in this DPhil emulate real medical practice as well as the areas of real medical practice that future work can focus on.

\
There are aspects of real medical practice not captured by the work presented in the DPhil. As discussed, many decisions in healthcare are made by groups of clinicians, rather than individuals. In both ICU and ED, I observed that it was common for staff to check their understanding with a colleague so that they did not miss any key considerations had they been working alone. In our studies, we tend to focus on the individual clinician and their own decisional process. Future work could focus on group confidence during diagnoses, which we noted as an underexplored area in past research based on our systematic scoping review. I would argue however that our work focusing on the individual decision maker is still important, as groups end up being an amalgamation of individual decision makers. If there are systematic tendencies toward overconfidence or underconfidence on the part of the individual, and a group is comprised of like-minded individuals, then individual tendencies would be amplified in a group (as per past social psychology research on ‘groupthink’). In addition, the individual decision making of those leading a shift (e.g. consultant, registrar) can have an impact on how others in the team make decisions. These reasons explain why our work focusing on individual decision-making processes is still important despite the group-based nature of clinical decision making.

\
Another aspect of note is that patient cases tend to take place over much longer timescales than our experimental procedures portray. Patients may be at the hospital for days, weeks or even months at a time. Emulating this longer timescale is difficult within a controlled experiment, but our VR study is useful for showing how patients change over time (albeit on a shortened timescale). Clinicians also have to deal with multiple cases at once, interleaving their attention between each. In our experiments, participants were able to focus on one patient case at a time. Interleaving attention between patients increases the cognitive load of clinicians and can increase the likelihood of clinicians becoming interrupted/distracted by other patients. As one paper in our scoping review showed, interruptions were shown to decrease confidence. Future work could include paradigms that involve multiple cases being diagnosed at once to investigate how appropriate confidence can be prompted. It was also observed that with more patients to manage at once, clinicians were prone to forgetting certain information or even mistaking one patient with another (which is especially understandable during night shifts). It is in these challenging healthcare environments that prompting information seeking that is appropriate to the clinicians’ current cognitive load could be a promising and important avenue for future work (e.g. prompting clinicians to avoid seeking too much information that they are then not likely to remember later on after seeing other patients).

\
I also note aspects of information seeking that future work could tap into based on the observations. As discussed, information can carry a cost in terms of time and may not always be available when needed. This can decrease confidence if clinicians have to continue with a patient case when they are not able to get all the information they need. Future work can look at how the cost in terms of time (and even money in some cases) affects the decision to seek information. A clinician may have to then decide, for example, whether to proceed without a test or await a test result before doing anything else with the patient. Another aspect of information seeking observed was the unreliability of information at times. In particular, a patient is an important source of information, such as describing the nature of the pain they are experiencing. However, patients may not always be reliable in providing information. For example, they may exaggerate their condition in order to be treated quicker or to receive stronger medication. Patients may also not be proficient in the language that the clinician speaks, leading to difficulties in communication. Information from colleagues may be unreliable as well if they do not have an in-depth understanding of the patient. Finally, tests themselves have a degree of unreliability, as most tests have a specificity and sensitivity level such that there is a likelihood of either a false positive or false negative. This means that clinicians may have to seek another opinion, perform the test again or seek other information. During this thesis, the fine-grained nature of information seeking as it pertains to its cost-benefit and its reliability was not emulated. This is a facet of real medical practice that is again tricky to emulate experimentally but could yield interesting insights into the decisional process. I observed for example that seeking a test is usually associated with a particular goal. A test is usually requested to query a particular diagnosis. One example I observed was a request for a D Dimer where a positive was actually ‘not diagnostic’ for a particular condition, whilst a negative result was considered ‘more informative.’ This indicates a certain strategic aspect to information seeking that we are yet to fully understand, especially with regards to confidence, given the more simplistic depiction of information seeking in our work and in the extant literature. 

\
There are, however, aspects of the studies in this thesis that do emulate real medical decisions. For one, situations of uncertainty arise frequently in healthcare, validating its need for further study. Uncertainty arises due to a multitude of factors related to patients, clinicians and the healthcare environment (as found from our systematic scoping review). Patients may present with symptoms that are suggestive of several diagnostic differentials (e.g. chest pain), leading to uncertainty that clinicians seek to resolve by seeking further information from the patient, from other clinicians or from their own examinations and testing. The overall flow of clinician decisional processes tends to follow that depicted in our studies: clinicians first develop an understanding of the patient’s medical history, perform some physical examinations of the patient based on the presenting symptoms and finally performing tests to either confirm their suspected diagnoses or rule out serious diagnoses. Uncertainty can arise from competing diagnoses, particularly when a potential diagnosis is common and hence most likely, whilst another is rarer but more serious if missed. This interplay between what is likely and what is serious was observed frequently in real medical settings. Uncertainty also arises from atypical patient cases, particularly when other comorbidities are involved. These manifest in fairly different patient presentations to the prototypical ‘textbook’ case of a condition. An observed example in ED was a patient who reported vision loss in one eye that was suspected to be a result of Giant Cell Arteritis (GCA, also known as Temporal Arteritis or TA). The type of vision loss that the patient experienced  was fairly unusual for a patient with this condition, as it was gradual degradation rather than a sudden loss. In our studies, we sought to balance the emulation of patient conditions that medical students could expect to see in their medical practice, whilst also using some atypicality in the patient’s presentation to prompt diagnostic uncertainty. Based on observations, it can be surmised that real medical decisions can often involve patients who do not fall within the ‘textbook’ definition of a condition. Hence, using such cases is a valid method for simulating diagnostic uncertainty in a controlled experiment. 

\
We also note that uncertainty can come from incomplete information. Whilst the information available on patients in our studies was limited, such situations also occur in real life too. For example, whilst the hospital I observed made use of an electronic system for recording all patient documentation and scans, such centralisation of information is not always the case in healthcare. This can be especially pertinent in less economically developed nations where there is less access to technology to aid clinicians in their decision making. One paper looking at healthcare handover and communication in India (Humphries et al., 2018) found that there was a reliance on patients to manage their own documentation, often “poorly recorded on unstructured sheets of paper”. Even within the medical setting I observed, there were differences in how clinicians recorded information on the patient. This led to a few observed situations where there was confusion expressed based on notes that a previous clinician (who had been treating the same patient) recorded being too vague. Clinicians may also rely on verbal reports from the patient as a source of information, but patients can be unreliable, uncooperative or in an unstable mental state to be able to produce key information (e.g. describing the nature of their pain). These factors together show how clinicians sometimes have to operate without having all the information they may ideally want to make a decision. Hence, whilst our studies (particular the vignette studies) are fairly limited in the information they provide on the patients, this is actually analogous to real situations that clinicians may encounter during practice and the uncertainty associated with the lack of complete information.  

\
Another aspect to note is that our work emulates is how clinicians’ thinking evolves over time with more information. Whilst the time course of our studies’ cases is much shorter than patients in real-life, they do capture (in a shortened fashion) how the receipt of information can change clinicians’ thought processes and their confidence in their decisions. This is where a real strength of this work can be observed, in that diagnosis is not a singular decision but an evolving process that we aimed to capture in our studies. Crucially, we also allow some freedom in our vignette studies for participants to cease information seeking when they deem appropriate. This allows us to capture differences in approaches to information seeking. One observed doctor in ED wanted to seek a chest X-Ray despite already having a chest MRI and this was seen as a precautionary measure for the patient that other doctors may not choose to do. The differences in what information to seek and when to stop seeking information seeking was observed to vary between clinicians, and we capture this aspect throughout our studies. This reflects how different clinicians may have their own tendencies when making decisions. These tendencies are what we aimed to operationalise more formally using our think-aloud study. There is still more work that can be done to study the sources of these individual differences in decision making, particularly on systematic tendencies toward underconfidence or overconfidence. Differences between clinicians were especially apparent when observing clinicians interact, as there were disagreements over, for example, whether certain tests were needed and how serious a patient was. As mentioned before, whilst most medical decisions are made by groups rather than individuals, studying individual factors that affect decision making is important when individual tendencies become apparent in a group.

\
In summary, I observed there to be some key aspects of medical decisions as they occur in real practice that we emulated in our empirical studies. Whilst there are other characteristics of medical decisions that we also cover in our work, these can be considered more as opportunities for future work rather than limitations with our current work. We believe there is sizeable scope for future research to delve even further into the cognitive psychology that underpin medical decisions made by clinicians, especially as they play out in everyday healthcare settings. For instance, there is work to be done on how contextual factors impact diagnostic confidence. When reviewing the extant literature studying surgeons' cognitive biases, Armonstrong et al. (2023) found that the vast majority of papers only looked at person-based sources of biases, rather than environmental and contextual factors. If a clinician encounters a patient with a broad set of differentials, they may have to seek more information to arrive at a final decision. If however the clinician was also more pressed for time due to other patients requiring attention, this limits the time that they can spend with the patient. This means that the clinician is under a time pressure to make a decision, as well as less of a scope for seeking further information. As discussed previously with an observed ED registrar, a clinician may see patients quickly to identify serious/urgent cases, thereby being consciously less thorough in their decisional process. What this indicates is that clinical reasoning does not have a 'one-size-fits-all' approach that works for all medical situations. Rather, clinical decision making can take many forms and requires clinicians to adapt their approach based on the patient and context. As observed in ICU and ED, real medicine is messy and constantly evolving and, as such, the study of medical decision making should adapt to reflect this.
